# carddataclass.py
"""Card data class with attributes, data attributes,
autogenerated methods and explicitly define methods."""
from dataclasses import dataclass
from typing import ClassVar, List

@dataclass
class Card:
    FACES: ClassVar[List[str]] = ['Ace','2', '3', '4', '5', '6', '7',
                                  '8', '9', '10', 'Jack', 'Queen', 'King']
    SUITS: ClassVar[List[str]] = ['Hearts', 'Diamonds', 'Clubs', 'Spades']
    
    face: str
    suit: str
    @property
    def image_name(self):
        """Return the Card's image file name."""
        return str(self).replace(' ', '_') +'.png'

    def __str__(self):
        """Return string representation for str()."""
        return f'{self.face} of {self.suit}'
    
    def __format__(self, format):
        """Return formatted string representation."""
        return f'{str(self):{format}}'